name: R_rstudio20240523
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - r-devtools
  - r-biocmanager
  - bioconductor-rsamtools
  - bioconductor-genomicranges
#  - r-refgenome
  - r-rcolorbrewer
  - r-wesanderson
  - r-nloptr
  - r-zoo 
  - bioconductor-ballgown
#optional packages - for rstudio
  - r-ggpubr
  - rstudio-desktop
# other packages
  - r-glue
  - r-data.table
  - r-dplyr
  - bioconductor-complexheatmap
  - r-gtools
  - bioconductor-summarizedexperiment
  - r-ggpmisc
